
package org.nanterreU.fr.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatriceServiceRemote", targetNamespace = "http://ws.fr.nanterreU.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatriceServiceRemote {


    /**
     * 
     * @param operande1
     * @param operande2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplier", targetNamespace = "http://ws.fr.nanterreU.org/", className = "org.nanterreU.fr.ws.Multiplier")
    @ResponseWrapper(localName = "multiplierResponse", targetNamespace = "http://ws.fr.nanterreU.org/", className = "org.nanterreU.fr.ws.MultiplierResponse")
    public double multiplier(
        @WebParam(name = "operande1", targetNamespace = "")
        double operande1,
        @WebParam(name = "operande2", targetNamespace = "")
        double operande2);

    /**
     * 
     * @param operande1
     * @param operande2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "additionner", targetNamespace = "http://ws.fr.nanterreU.org/", className = "org.nanterreU.fr.ws.Additionner")
    @ResponseWrapper(localName = "additionnerResponse", targetNamespace = "http://ws.fr.nanterreU.org/", className = "org.nanterreU.fr.ws.AdditionnerResponse")
    public double additionner(
        @WebParam(name = "operande1", targetNamespace = "")
        double operande1,
        @WebParam(name = "operande2", targetNamespace = "")
        double operande2);

}
