package org.nanterreU.fr.client;

/**
 * Java client for the Calculatrice SOAP Web Service.
 *
 * BEFORE compiling this class, generate the client stubs with wsimport:
 *
 *   wsimport -keep -s src -d bin -p org.nanterreU.fr.ws http://localhost:8080/CalculatriceWS/CalculatriceService?wsdl
 *
 * This generates two classes in org.nanterreU.fr.ws:
 *   - CalculatriceService       (the service locator, extends javax.xml.ws.Service)
 *   - CalculatriceServiceRemote (the SEI port interface with additionner / multiplier)
 */

// These imports come from the classes generated by wsimport:
import org.nanterreU.fr.ws.CalculatriceService;
import org.nanterreU.fr.ws.CalculatriceServiceRemote;

public class ClientMain {

    public static void main(String[] args) {

        // 1. Create the service (locates the WSDL and builds the proxy)
        CalculatriceService service = new CalculatriceService();

        // 2. Get the port (the generated proxy that speaks SOAP over HTTP)
        CalculatriceServiceRemote port = service.getCalculatriceServicePort();

        // 3. Call the remote operation
        double operande1 = 2;
        double operande2 = 33;
        double result = port.additionner(operande1, operande2);

        // 4. Print the result
        System.out.println("additionner(" + operande1 + ", " + operande2 + ") = " + result);
    }
}
